<?php
/**
 * Site
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Duda
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Site Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Site implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Site';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_name' => 'string',
        'external_uid' => 'string',
        'site_domain' => 'string',
        'lang' => 'string',
        'site_business_info' => '\OpenAPI\Client\Model\SiteBusinessInfo',
        'site_alternate_domains' => '\OpenAPI\Client\Model\SiteSiteAlternateDomains',
        'site_seo' => '\OpenAPI\Client\Model\Seo',
        'schemas' => '\OpenAPI\Client\Model\SiteSchemas',
        'site_name' => 'string',
        'template_id' => 'string',
        'site_default_domain' => 'string',
        'preview_site_url' => 'string',
        'last_published_date' => 'string',
        'first_published_date' => 'string',
        'force_https' => 'string',
        'last_reset_by' => 'string',
        'certificate_status' => 'string',
        'modification_date' => 'string',
        'creation_date' => 'string',
        'publish_status' => 'string',
        'thumbnail_url' => 'string',
        'store_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_name' => null,
        'external_uid' => null,
        'site_domain' => null,
        'lang' => null,
        'site_business_info' => null,
        'site_alternate_domains' => null,
        'site_seo' => null,
        'schemas' => null,
        'site_name' => null,
        'template_id' => null,
        'site_default_domain' => null,
        'preview_site_url' => null,
        'last_published_date' => null,
        'first_published_date' => null,
        'force_https' => null,
        'last_reset_by' => null,
        'certificate_status' => null,
        'modification_date' => null,
        'creation_date' => null,
        'publish_status' => null,
        'thumbnail_url' => null,
        'store_status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_name' => 'account_name',
        'external_uid' => 'external_uid',
        'site_domain' => 'site_domain',
        'lang' => 'lang',
        'site_business_info' => 'site_business_info',
        'site_alternate_domains' => 'site_alternate_domains',
        'site_seo' => 'site_seo',
        'schemas' => 'schemas',
        'site_name' => 'site_name',
        'template_id' => 'template_id',
        'site_default_domain' => 'site_default_domain',
        'preview_site_url' => 'preview_site_url',
        'last_published_date' => 'last_published_date',
        'first_published_date' => 'first_published_date',
        'force_https' => 'force_https',
        'last_reset_by' => 'last_reset_by',
        'certificate_status' => 'certificate_status',
        'modification_date' => 'modification_date',
        'creation_date' => 'creation_date',
        'publish_status' => 'publish_status',
        'thumbnail_url' => 'thumbnail_url',
        'store_status' => 'store_status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_name' => 'setAccountName',
        'external_uid' => 'setExternalUid',
        'site_domain' => 'setSiteDomain',
        'lang' => 'setLang',
        'site_business_info' => 'setSiteBusinessInfo',
        'site_alternate_domains' => 'setSiteAlternateDomains',
        'site_seo' => 'setSiteSeo',
        'schemas' => 'setSchemas',
        'site_name' => 'setSiteName',
        'template_id' => 'setTemplateId',
        'site_default_domain' => 'setSiteDefaultDomain',
        'preview_site_url' => 'setPreviewSiteUrl',
        'last_published_date' => 'setLastPublishedDate',
        'first_published_date' => 'setFirstPublishedDate',
        'force_https' => 'setForceHttps',
        'last_reset_by' => 'setLastResetBy',
        'certificate_status' => 'setCertificateStatus',
        'modification_date' => 'setModificationDate',
        'creation_date' => 'setCreationDate',
        'publish_status' => 'setPublishStatus',
        'thumbnail_url' => 'setThumbnailUrl',
        'store_status' => 'setStoreStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_name' => 'getAccountName',
        'external_uid' => 'getExternalUid',
        'site_domain' => 'getSiteDomain',
        'lang' => 'getLang',
        'site_business_info' => 'getSiteBusinessInfo',
        'site_alternate_domains' => 'getSiteAlternateDomains',
        'site_seo' => 'getSiteSeo',
        'schemas' => 'getSchemas',
        'site_name' => 'getSiteName',
        'template_id' => 'getTemplateId',
        'site_default_domain' => 'getSiteDefaultDomain',
        'preview_site_url' => 'getPreviewSiteUrl',
        'last_published_date' => 'getLastPublishedDate',
        'first_published_date' => 'getFirstPublishedDate',
        'force_https' => 'getForceHttps',
        'last_reset_by' => 'getLastResetBy',
        'certificate_status' => 'getCertificateStatus',
        'modification_date' => 'getModificationDate',
        'creation_date' => 'getCreationDate',
        'publish_status' => 'getPublishStatus',
        'thumbnail_url' => 'getThumbnailUrl',
        'store_status' => 'getStoreStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_name'] = $data['account_name'] ?? null;
        $this->container['external_uid'] = $data['external_uid'] ?? null;
        $this->container['site_domain'] = $data['site_domain'] ?? null;
        $this->container['lang'] = $data['lang'] ?? null;
        $this->container['site_business_info'] = $data['site_business_info'] ?? null;
        $this->container['site_alternate_domains'] = $data['site_alternate_domains'] ?? null;
        $this->container['site_seo'] = $data['site_seo'] ?? null;
        $this->container['schemas'] = $data['schemas'] ?? null;
        $this->container['site_name'] = $data['site_name'] ?? null;
        $this->container['template_id'] = $data['template_id'] ?? null;
        $this->container['site_default_domain'] = $data['site_default_domain'] ?? null;
        $this->container['preview_site_url'] = $data['preview_site_url'] ?? null;
        $this->container['last_published_date'] = $data['last_published_date'] ?? null;
        $this->container['first_published_date'] = $data['first_published_date'] ?? null;
        $this->container['force_https'] = $data['force_https'] ?? null;
        $this->container['last_reset_by'] = $data['last_reset_by'] ?? null;
        $this->container['certificate_status'] = $data['certificate_status'] ?? null;
        $this->container['modification_date'] = $data['modification_date'] ?? null;
        $this->container['creation_date'] = $data['creation_date'] ?? null;
        $this->container['publish_status'] = $data['publish_status'] ?? null;
        $this->container['thumbnail_url'] = $data['thumbnail_url'] ?? null;
        $this->container['store_status'] = $data['store_status'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_name
     *
     * @return string|null
     */
    public function getAccountName()
    {
        return $this->container['account_name'];
    }

    /**
     * Sets account_name
     *
     * @param string|null $account_name account_name
     *
     * @return self
     */
    public function setAccountName($account_name)
    {
        $this->container['account_name'] = $account_name;

        return $this;
    }

    /**
     * Gets external_uid
     *
     * @return string|null
     */
    public function getExternalUid()
    {
        return $this->container['external_uid'];
    }

    /**
     * Sets external_uid
     *
     * @param string|null $external_uid external_uid
     *
     * @return self
     */
    public function setExternalUid($external_uid)
    {
        $this->container['external_uid'] = $external_uid;

        return $this;
    }

    /**
     * Gets site_domain
     *
     * @return string|null
     */
    public function getSiteDomain()
    {
        return $this->container['site_domain'];
    }

    /**
     * Sets site_domain
     *
     * @param string|null $site_domain site_domain
     *
     * @return self
     */
    public function setSiteDomain($site_domain)
    {
        $this->container['site_domain'] = $site_domain;

        return $this;
    }

    /**
     * Gets lang
     *
     * @return string|null
     */
    public function getLang()
    {
        return $this->container['lang'];
    }

    /**
     * Sets lang
     *
     * @param string|null $lang lang
     *
     * @return self
     */
    public function setLang($lang)
    {
        $this->container['lang'] = $lang;

        return $this;
    }

    /**
     * Gets site_business_info
     *
     * @return \OpenAPI\Client\Model\SiteBusinessInfo|null
     */
    public function getSiteBusinessInfo()
    {
        return $this->container['site_business_info'];
    }

    /**
     * Sets site_business_info
     *
     * @param \OpenAPI\Client\Model\SiteBusinessInfo|null $site_business_info site_business_info
     *
     * @return self
     */
    public function setSiteBusinessInfo($site_business_info)
    {
        $this->container['site_business_info'] = $site_business_info;

        return $this;
    }

    /**
     * Gets site_alternate_domains
     *
     * @return \OpenAPI\Client\Model\SiteSiteAlternateDomains|null
     */
    public function getSiteAlternateDomains()
    {
        return $this->container['site_alternate_domains'];
    }

    /**
     * Sets site_alternate_domains
     *
     * @param \OpenAPI\Client\Model\SiteSiteAlternateDomains|null $site_alternate_domains site_alternate_domains
     *
     * @return self
     */
    public function setSiteAlternateDomains($site_alternate_domains)
    {
        $this->container['site_alternate_domains'] = $site_alternate_domains;

        return $this;
    }

    /**
     * Gets site_seo
     *
     * @return \OpenAPI\Client\Model\Seo|null
     */
    public function getSiteSeo()
    {
        return $this->container['site_seo'];
    }

    /**
     * Sets site_seo
     *
     * @param \OpenAPI\Client\Model\Seo|null $site_seo site_seo
     *
     * @return self
     */
    public function setSiteSeo($site_seo)
    {
        $this->container['site_seo'] = $site_seo;

        return $this;
    }

    /**
     * Gets schemas
     *
     * @return \OpenAPI\Client\Model\SiteSchemas|null
     */
    public function getSchemas()
    {
        return $this->container['schemas'];
    }

    /**
     * Sets schemas
     *
     * @param \OpenAPI\Client\Model\SiteSchemas|null $schemas schemas
     *
     * @return self
     */
    public function setSchemas($schemas)
    {
        $this->container['schemas'] = $schemas;

        return $this;
    }

    /**
     * Gets site_name
     *
     * @return string|null
     */
    public function getSiteName()
    {
        return $this->container['site_name'];
    }

    /**
     * Sets site_name
     *
     * @param string|null $site_name site_name
     *
     * @return self
     */
    public function setSiteName($site_name)
    {
        $this->container['site_name'] = $site_name;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param string|null $template_id template_id
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        $this->container['template_id'] = $template_id;

        return $this;
    }

    /**
     * Gets site_default_domain
     *
     * @return string|null
     */
    public function getSiteDefaultDomain()
    {
        return $this->container['site_default_domain'];
    }

    /**
     * Sets site_default_domain
     *
     * @param string|null $site_default_domain site_default_domain
     *
     * @return self
     */
    public function setSiteDefaultDomain($site_default_domain)
    {
        $this->container['site_default_domain'] = $site_default_domain;

        return $this;
    }

    /**
     * Gets preview_site_url
     *
     * @return string|null
     */
    public function getPreviewSiteUrl()
    {
        return $this->container['preview_site_url'];
    }

    /**
     * Sets preview_site_url
     *
     * @param string|null $preview_site_url preview_site_url
     *
     * @return self
     */
    public function setPreviewSiteUrl($preview_site_url)
    {
        $this->container['preview_site_url'] = $preview_site_url;

        return $this;
    }

    /**
     * Gets last_published_date
     *
     * @return string|null
     */
    public function getLastPublishedDate()
    {
        return $this->container['last_published_date'];
    }

    /**
     * Sets last_published_date
     *
     * @param string|null $last_published_date last_published_date
     *
     * @return self
     */
    public function setLastPublishedDate($last_published_date)
    {
        $this->container['last_published_date'] = $last_published_date;

        return $this;
    }

    /**
     * Gets first_published_date
     *
     * @return string|null
     */
    public function getFirstPublishedDate()
    {
        return $this->container['first_published_date'];
    }

    /**
     * Sets first_published_date
     *
     * @param string|null $first_published_date first_published_date
     *
     * @return self
     */
    public function setFirstPublishedDate($first_published_date)
    {
        $this->container['first_published_date'] = $first_published_date;

        return $this;
    }

    /**
     * Gets force_https
     *
     * @return string|null
     */
    public function getForceHttps()
    {
        return $this->container['force_https'];
    }

    /**
     * Sets force_https
     *
     * @param string|null $force_https force_https
     *
     * @return self
     */
    public function setForceHttps($force_https)
    {
        $this->container['force_https'] = $force_https;

        return $this;
    }

    /**
     * Gets last_reset_by
     *
     * @return string|null
     */
    public function getLastResetBy()
    {
        return $this->container['last_reset_by'];
    }

    /**
     * Sets last_reset_by
     *
     * @param string|null $last_reset_by last_reset_by
     *
     * @return self
     */
    public function setLastResetBy($last_reset_by)
    {
        $this->container['last_reset_by'] = $last_reset_by;

        return $this;
    }

    /**
     * Gets certificate_status
     *
     * @return string|null
     */
    public function getCertificateStatus()
    {
        return $this->container['certificate_status'];
    }

    /**
     * Sets certificate_status
     *
     * @param string|null $certificate_status certificate_status
     *
     * @return self
     */
    public function setCertificateStatus($certificate_status)
    {
        $this->container['certificate_status'] = $certificate_status;

        return $this;
    }

    /**
     * Gets modification_date
     *
     * @return string|null
     */
    public function getModificationDate()
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     *
     * @param string|null $modification_date modification_date
     *
     * @return self
     */
    public function setModificationDate($modification_date)
    {
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return string|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param string|null $creation_date creation_date
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets publish_status
     *
     * @return string|null
     */
    public function getPublishStatus()
    {
        return $this->container['publish_status'];
    }

    /**
     * Sets publish_status
     *
     * @param string|null $publish_status publish_status
     *
     * @return self
     */
    public function setPublishStatus($publish_status)
    {
        $this->container['publish_status'] = $publish_status;

        return $this;
    }

    /**
     * Gets thumbnail_url
     *
     * @return string|null
     */
    public function getThumbnailUrl()
    {
        return $this->container['thumbnail_url'];
    }

    /**
     * Sets thumbnail_url
     *
     * @param string|null $thumbnail_url thumbnail_url
     *
     * @return self
     */
    public function setThumbnailUrl($thumbnail_url)
    {
        $this->container['thumbnail_url'] = $thumbnail_url;

        return $this;
    }

    /**
     * Gets store_status
     *
     * @return string|null
     */
    public function getStoreStatus()
    {
        return $this->container['store_status'];
    }

    /**
     * Sets store_status
     *
     * @param string|null $store_status store_status
     *
     * @return self
     */
    public function setStoreStatus($store_status)
    {
        $this->container['store_status'] = $store_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


