<?php
/**
 * PagesV2ApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Duda
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PagesV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PagesV2ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sitesMultiscreenSiteNamePagesGet
     *
     * Get details of all the Pages of a Site..
     *
     */
    public function testSitesMultiscreenSiteNamePagesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitesMultiscreenSiteNamePagesPageUuidDelete
     *
     * Delete a Page from a Site..
     *
     */
    public function testSitesMultiscreenSiteNamePagesPageUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitesMultiscreenSiteNamePagesPageUuidDuplicatePost
     *
     * Duplicate an existing Page of a Site..
     *
     */
    public function testSitesMultiscreenSiteNamePagesPageUuidDuplicatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitesMultiscreenSiteNamePagesPageUuidGet
     *
     * Get the details of an individual Page of a Site..
     *
     */
    public function testSitesMultiscreenSiteNamePagesPageUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitesMultiscreenSiteNamePagesPageUuidPut
     *
     * Update an existing Page of a Site..
     *
     */
    public function testSitesMultiscreenSiteNamePagesPageUuidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
